[package]
name = "test_from_derive"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "test_from_derive"
path = "test_from_derive.rs"

[dependencies]
theta = { path = "theta" }
tokio = { version = "1.0", features = ["full"] }
anyhow = "1.0"
serde = { version = "1.0", features = ["derive"] }
