[package]
name = "theta"
version = "0.1.0-alpha.0"
edition = "2024"
authors = ["Chanwoo Ahn <cwahn0904@gmail.com>"]
license = "MIT"
description = "An Rust Actor Framework"                  # Required
repository = "https://github.com/cwahn/theta"            # Recommended
readme = "README.md"
keywords = ["async", "actor", "concurrency"]             # Optional, max 5 keywords
categories = ["asynchronous", "concurrency"]
exclude = ["benches/", "examples/", ".github/", "*.tmp"]

[dependencies]
anyhow = "1.0.98"
futures = "0.3.31"
inventory = "0.3.20"
linkme = "0.3.33"
serde = { version = "1.0.219", features = ["derive"] }
tokio = { version = "1.46.1", features = ["sync", "rt", "time", "macros"] }
tracing = "0.1.41"

[dev-dependencies]
tokio = { version = "1.46.1", features = [
    "sync",
    "rt",
    "time",
    "macros",
    "rt-multi-thread",
] }
criterion = "0.6.0"
kanal = "0.1.1"

[[bench]]
name = "channel"
harness = false
path = "benches/channel.rs"
