[package]
name = "theta"
version = "0.1.0-alpha.0"
edition = "2024"
authors = ["Chanwoo Ahn <cwahn0904@gmail.com>"]
license = "MIT"
description = "An Rust Actor Framework"
repository = "https://github.com/cwahn/theta"
readme = "README.md"
keywords = ["async", "actor", "concurrency"]
categories = ["asynchronous", "concurrency"]
exclude = ["benches/", "examples/", ".github/", "*.tmp"]

[features]
default = ["full"]
full = ["macros", "persistence", "remote", "tracing"]
macros = ["theta-macros"]
persistence = ["url", "postcard", "theta-macros?/persistence"]
remote = [
    "iroh",
    "linkme",
    "serde_flexitos",
    "erased-serde",
    "theta-macros?/remote",
]
tracing = ["dep:tracing"]
linkme = ["dep:linkme"]

[dependencies]
futures = "0.3.31"
serde = { version = "1.0.219", features = ["derive"] }
tokio = { version = "1.46.1", features = ["sync", "rt", "time", "macros"] }
uuid = { version = "1.17.0", features = ["v4", "serde"] }
paste = "1.0.15"
rustc-hash = "2.1.1"
anyhow = "1.0.98"                                                           # todo Use custom error 
serde_json = "1.0.141"                                                      # ! temp for serialization-dev

theta-macros = { path = "../theta-macros", optional = true }
tracing = { version = "0.1.41", optional = true }
postcard = { version = "1.1.2", features = ["use-std"], optional = true }
serde_flexitos = { version = "0.2.2", optional = true }
url = { version = "2.5.4", features = ["serde"], optional = true }
iroh = { version = "0.90.0", optional = true }
linkme = { version = "0.3.33", optional = true }
erased-serde = { version = "0.4.6", optional = true }                     # ! temp for deser test
bytes = "1.10.1"


# url = "2.5.4"
[dev-dependencies]
tokio = { version = "1.46.1", features = [
    "sync",
    "rt",
    "time",
    "macros",
    "rt-multi-thread",
] }
tempfile = "3.20.0"
criterion = "0.6.0"

[[bench]]
name = "channel"
harness = false
path = "benches/channel.rs"
