[package]
name = "theta"
version = "0.1.0-alpha.0"
edition = "2024"
authors = ["Chanwoo Ahn <cwahn0904@gmail.com>"]
license = "MIT"
description = "An Rust Actor Framework"
repository = "https://github.com/cwahn/theta"
readme = "README.md"
keywords = ["async", "actor", "concurrency"]
categories = ["asynchronous", "concurrency"]
exclude = ["benches/", "examples/", ".github/", "*.tmp"]

[features]
default = ["full"]
full = ["macros", "persistence", "remote", "max_level_debug"]
macros = ["theta-macros"]
persistence = ["url", "postcard", "theta-macros?/persistence"]
remote = ["theta-macros?/remote", "theta-protocol"]

# Tracing levels
max_level_off = ["tracing/max_level_off"]
max_level_error = ["tracing/max_level_error"]
max_level_warn = ["tracing/max_level_warn"]
max_level_info = ["tracing/max_level_info"]
max_level_debug = ["tracing/max_level_debug"]
max_level_trace = ["tracing/max_level_trace"]
release_max_level_off = ["tracing/release_max_level_off"]
release_max_level_error = ["tracing/release_max_level_error"]
release_max_level_warn = ["tracing/release_max_level_warn"]
release_max_level_info = ["tracing/release_max_level_info"]
release_max_level_debug = ["tracing/release_max_level_debug"]
release_max_level_trace = ["tracing/release_max_level_trace"]


[dependencies]
serde = { version = "1.0.219", features = ["derive"] }
tokio = { version = "1.46.1", features = ["sync", "rt", "time", "macros"] }
uuid = { version = "1.17.0", features = ["v4", "serde"] }
rustc-hash = "2.1.1"
anyhow = "1.0.98"                                                           # todo Use custom error 
inventory = "0.3.20"                                                        # todo Should move to linkme when it supports WASM
directories = "6.0.0"
rand = "0.8"
theta-flume = "0.11.4"
futures = "0.3.31"
thiserror = "2.0.14"

tracing = { version = "0.1.41", optional = true }
theta-protocol = { git = "https://github.com/cwahn/theta-protocol", branch = "feat/iroh2", optional = true }
theta-macros = { path = "../theta-macros", optional = true }
postcard = { version = "1.1.2", features = ["use-std"], optional = true }
url = { version = "2.5.4", features = ["serde"], optional = true }

# WASM support

[target.'cfg(target_arch = "wasm32")'.dependencies]
getrandom = { version = "0.3", features = ["wasm_js"] }
uuid = { version = "1.17.0", features = ["v4", "serde", "rng-getrandom"] }

[dev-dependencies]
tracing-subscriber = { version = "0.3.19", features = ["env-filter", "chrono"] }
tempfile = "3.20.0"


[[example]]
name = "ping_pong"


[[bench]]
name = "channel"
harness = false
path = "benches/channel.rs"
