// theta-actors.d.ts is auto-generated by vite-plugin-theta on first `npm run dev`.
// The import below is correct at runtime — IDE may show errors before first build.
import {
  initTheta,
  lookupDepot,
  type DepotRef,
  type ItemRef,
  type Bundle,
  type Group,
  type Container,
} from 'theta:actors'

interface TestCase {
  name: string
  passed: boolean
  error?: string
}

/** Reject a promise if it doesn't settle within `ms` milliseconds. */
function withTimeout<T>(p: Promise<T>, ms: number, label: string): Promise<T> {
  return Promise.race([
    p,
    new Promise<T>((_, reject) =>
      setTimeout(() => reject(new Error(`timeout after ${ms}ms — ${label}`)), ms),
    ),
  ])
}

function addResult(results: HTMLElement, tc: TestCase): void {
  const el = document.createElement('div')
  el.className = `test-case ${tc.passed ? 'pass' : 'fail'}`
  el.dataset.name = tc.name
  el.dataset.passed = String(tc.passed)
  el.textContent = `${tc.passed ? '✓' : '✗'} ${tc.name}${tc.error ? ': ' + tc.error : ''}`
  results.appendChild(el)
  console.log(`[theta-test] ${el.textContent}`)
}

async function run(): Promise<void> {
  const status = document.getElementById('status')!
  const results = document.getElementById('results')!

  const params = new URLSearchParams(window.location.search)
  const peerKey = params.get('peer')

  if (!peerKey) {
    status.textContent = 'ERROR: no ?peer= query param'
    results.dataset.done = 'true'
    return
  }

  try {
    status.textContent = 'Initialising WASM runtime…'
    await initTheta()

    status.textContent = `Connecting to native peer ${peerKey.slice(0, 8)}…`
    console.log(`[theta-test] lookupDepot iroh://depot@${peerKey}`)
    const depot: DepotRef = await withTimeout(
      lookupDepot(`iroh://depot@${peerKey}`),
      60_000,
      'lookupDepot',
    )
    console.log('[theta-test] depot connected')
    status.textContent = 'Running tests…'

    // ── T1: ActorRef as return value ─────────────────────────────────────────
    try {
      const itemRef: ItemRef = await withTimeout(
        depot.ask({ SpawnItem: { label: 'roundtrip-t1' } }),
        5_000, 'SpawnItem T1',
      )
      const pong: string = await withTimeout(itemRef.ask({ Ping: {} }), 5_000, 'Ping T1')
      addResult(results, {
        name: 'T1: ActorRef as return value',
        passed: pong === 'pong:roundtrip-t1',
        error: pong !== 'pong:roundtrip-t1' ? `got '${pong}'` : undefined,
      })
    } catch (e) {
      addResult(results, { name: 'T1: ActorRef as return value', passed: false, error: String(e) })
    }

    // ── T2: ActorRef as message field (relay) ─────────────────────────────────
    try {
      const itemRef: ItemRef = await withTimeout(
        depot.ask({ SpawnItem: { label: 'roundtrip-t2' } }),
        5_000, 'SpawnItem T2',
      )
      const relayed: string = await withTimeout(
        depot.ask({ Relay: { target: itemRef } }),
        5_000, 'Relay T2',
      )
      addResult(results, {
        name: 'T2: ActorRef as message field (relay)',
        passed: relayed === 'pong:roundtrip-t2',
        error: relayed !== 'pong:roundtrip-t2' ? `got '${relayed}'` : undefined,
      })
    } catch (e) {
      addResult(results, {
        name: 'T2: ActorRef as message field (relay)',
        passed: false,
        error: String(e),
      })
    }

    // ── T3: struct with two ActorRef fields ──────────────────────────────────
    try {
      const bundle: Bundle = await withTimeout(depot.ask({ GetBundle: {} }), 5_000, 'GetBundle')
      const pongA: string = await withTimeout(bundle.a.ask({ Ping: {} }), 5_000, 'Ping T3a')
      const pongB: string = await withTimeout(bundle.b.ask({ Ping: {} }), 5_000, 'Ping T3b')
      addResult(results, {
        name: 'T3: struct with two ActorRef fields',
        passed: pongA.startsWith('pong:') && pongB.startsWith('pong:'),
        error:
          !pongA.startsWith('pong:') || !pongB.startsWith('pong:')
            ? `a='${pongA}' b='${pongB}'`
            : undefined,
      })
    } catch (e) {
      addResult(results, {
        name: 'T3: struct with two ActorRef fields',
        passed: false,
        error: String(e),
      })
    }

    // ── T4: Vec<ActorRef> ────────────────────────────────────────────────────
    try {
      const group: Group = await withTimeout(depot.ask({ GetGroup: {} }), 5_000, 'GetGroup')
      const pongs: string[] = await withTimeout(
        Promise.all(group.members.map((m) => m.ask({ Ping: {} }) as Promise<string>)),
        5_000, 'Ping T4 all',
      )
      const allOk = pongs.every((p) => p.startsWith('pong:'))
      addResult(results, {
        name: 'T4: Vec<ActorRef> round-trip',
        passed: allOk,
        error: !allOk ? `pongs=[${pongs.join(', ')}]` : undefined,
      })
    } catch (e) {
      addResult(results, { name: 'T4: Vec<ActorRef> round-trip', passed: false, error: String(e) })
    }

    // ── T5: nested struct with ActorRef at leaf ──────────────────────────────
    try {
      const container: Container = await withTimeout(depot.ask({ GetNested: {} }), 5_000, 'GetNested')
      const pong: string = await withTimeout(container.inner.item.ask({ Ping: {} }), 5_000, 'Ping T5')
      addResult(results, {
        name: 'T5: nested struct with ActorRef at leaf',
        passed: pong.startsWith('pong:'),
        error: !pong.startsWith('pong:') ? `got '${pong}'` : undefined,
      })
    } catch (e) {
      addResult(results, {
        name: 'T5: nested struct with ActorRef at leaf',
        passed: false,
        error: String(e),
      })
    }

    // ── T6: ref remains valid across multiple sequential round-trips ──────────
    try {
      const itemRef: ItemRef = await withTimeout(
        depot.ask({ SpawnItem: { label: 'roundtrip-t6' } }), 5_000, 'SpawnItem T6',
      )
      const p1: string = await withTimeout(itemRef.ask({ Ping: {} }), 5_000, 'Ping T6a')
      await withTimeout(itemRef.ask({ Bump: {} }), 5_000, 'Bump T6 x1')
      await withTimeout(itemRef.ask({ Bump: {} }), 5_000, 'Bump T6 x2')
      await withTimeout(itemRef.ask({ Bump: {} }), 5_000, 'Bump T6 x3')
      const count: number = await withTimeout(itemRef.ask({ GetCount: {} }), 5_000, 'GetCount T6')
      const p2: string = await withTimeout(itemRef.ask({ Ping: {} }), 5_000, 'Ping T6b')

      const passed =
        p1 === 'pong:roundtrip-t6' && count === 3 && p2 === 'pong:roundtrip-t6'
      addResult(results, {
        name: 'T6: ref validity persists across multiple uses',
        passed,
        error: !passed ? `p1='${p1}' count=${count} p2='${p2}'` : undefined,
      })
    } catch (e) {
      addResult(results, {
        name: 'T6: ref validity persists across multiple uses',
        passed: false,
        error: String(e),
      })
    }

    status.textContent = 'Done.'
  } catch (e) {
    const el = document.createElement('div')
    el.className = 'fatal'
    el.textContent = `Fatal: ${String(e)}`
    results.appendChild(el)
    status.textContent = 'Fatal error — see below.'
  }

  // Signal to Playwright that all tests have finished.
  results.dataset.done = 'true'
}

run()
