import fs from "fs";
import path from "path";
import type { ActorInfo } from "./actors.js";
import { writeIfChanged } from "./fs-util.js";

/**
 * Generate `theta-actors.d.ts` in the Vite project root so TypeScript
 * can resolve `import { ... } from 'theta:actors'` via tsconfig `paths`.
 *
 * The generated file re-exports everything from the wasm-pack .d.ts.
 * Users must add `"theta:actors": ["./theta-actors.d.ts"]` to tsconfig paths.
 */
export function generateTypeDeclaration(
  projectRoot: string,
  pkgDir: string,
  moduleName: string,
  actors: ActorInfo[] = [],
): void {
  // Use .js for path — bundler moduleResolution finds the adjacent .d.ts
  let relJs = path
    .relative(projectRoot, path.join(pkgDir, `${moduleName}.js`))
    .replace(/\\/g, "/");
  if (!relJs.startsWith(".")) {
    relJs = "./" + relJs;
  }

  const lines: string[] = [
    `// Auto-generated by vite-plugin-theta — do not edit`,
    `export * from '${relJs}';`,
    `export { default } from '${relJs}';`,
    `/** Initialise the Theta WASM runtime (wasm-bindgen init + iroh endpoint). Returns the local peer public key. */`,
    `export declare function initTheta(): Promise<string>;`,
  ];

  if (actors.length > 0) {
    // Import actor types needed for hook declarations
    const typeImports = actors.flatMap((a) => [a.refName, a.viewName]);
    lines.push(`import type { ${typeImports.join(", ")} } from '${relJs}';`);

    // Generic hooks re-exported from theta-ts/react
    lines.push(`export { useActorView, useActorRef } from 'theta-ts/react';`);

    // Per-actor hook aliases with overloaded signatures
    for (const actor of actors) {
      lines.push(`export declare function use${actor.name}View(ref: ${actor.refName} | null): ${actor.viewName} | null;`);
      lines.push(`export declare function use${actor.name}View<S>(ref: ${actor.refName} | null, selector: (state: ${actor.viewName}) => S, equalityFn?: (a: S, b: S) => boolean): S | null;`);
    }
  }

  writeIfChanged(path.join(projectRoot, "theta-actors.d.ts"), lines.join("\n") + "\n");
}
